version: "3.8"

# PROJECT NAME
name: "inception"

# SERVICES
services:
  # MARIADB
  mariadb:
    build:
      context: ./services/mariadb
    container_name: mariadb
    configs:
      - source: db_config
        target: /etc/my.cnf
    env_file: ./.env
    expose:
      - "3306"
    networks:
      backend:
        ipv4_address: 172.18.0.2
    volumes:
      - db_data:/var/lib/mysql
    restart: on-failure

  # WORDPRESS
  wordpress:
    build:
      context: ./services/wordpress
    container_name: wordpress
    configs:
      - source: php_config
        target: /etc/php7/php.ini
      - source: wp_config
        target: /etc/php7/php-fpm.d/www.conf
    depends_on:
      mariadb:
        condition: service_healthy
    env_file: ./.env
    expose:
      - "9000"
    networks:
      backend:
        ipv4_address: 172.18.0.3
    volumes:
      - wp_resources:/var/www/ghan.42.fr
    tty: on
    restart: on-failure

  # NGINX
  nginx:
    build:
      context: ./services/nginx
    container_name: nginx
    configs:
      - source: nginx_global_config
        target: /etc/nginx/nginx.conf
      - source: nginx_local_config
        target: /etc/nginx/conf.d/inception.conf
    depends_on:
      - wordpress
    env_file: ./.env
    expose:
      - "443"
    hostname: ghan.42.fr
    networks:
      backend:
        ipv4_address: 172.18.0.4
    volumes:
      - wp_resources:/var/www/ghan.42.fr
    restart: on-failure

# CONFIGS
configs:
  db_config:
    file: ./services/mariadb/configs/my.cnf
  nginx_global_config:
    file: ./services/nginx/configs/nginx.conf
  nginx_local_config:
    file: ./services/nginx/configs/ghan.42.fr.conf
  wp_config:
    file: ./services/wordpress/configs/www.conf
  php_config:
    file: ./services/wordpress/configs/php.ini

# NETWORKS
networks:
  backend:
    ipam:
      config:
        - subnet: 172.18.0.0/24
          ip_range: 172.28.0.0/24
          gateway: 172.18.0.1

# VOLUMES
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ghan/data/db
  wp_resources:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ghan/data/wp
