version: "3.8"

# PROJECT NAME
name: "inception"

# SERVICES
services:
  # MARIADB
  mariadb:
    build:
      context: ./services/mariadb
    image: mariadb
    container_name: mariadb
    configs:
      - source: db_config
        target: /etc/my.cnf
    env_file: ./.env
    expose:
      - "3306"
    hostname: inception_mariadb
    networks:
      backend:
        ipv4_address: 172.18.0.2
    volumes:
      - db_data:/var/lib/mysql
    restart: on-failure

  # WORDPRESS
  wordpress:
    build:
      context: ./services/wordpress
    image: wordpress
    container_name: wordpress
    configs:
      - source: wp_fpm_config
        target: /etc/php8/php.ini
      - source: wp_config
        target: /etc/php8/php-fpm.d/www.conf
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: ./.env
    expose:
      - "9000"
    hostname: inception_wordpress
    networks:
      backend:
        ipv4_address: 172.18.0.3
    volumes:
      - wp_resources:/var/www/ghan.42.fr
    tty: on
    restart: on-failure

  # NGINX
  nginx:
    build:
      context: ./services/nginx
    image: nginx
    container_name: nginx
    configs:
      - source: nginx_global_config
        target: /etc/nginx/nginx.conf
      - source: nginx_server_config
        target: /etc/nginx/conf.d/
    depends_on:
      - wordpress
      - adminer
      - static_www
    env_file: ./.env
    ports:
      - "443:443"
    hostname: ghan.42.fr
    networks:
      backend:
        ipv4_address: 172.18.0.4
    volumes:
      - wp_resources:/var/www/ghan.42.fr
      - adminer_resources:/var/www/adminer
      - static_resources:/var/www/static
    stop_signal: SIGQUIT
    restart: on-failure

  # ADMINER
  adminer:
    build:
      context: ./services/adminer
    image: adminer
    container_name: adminer
    configs:
      - source: adminer_fpm_config
        target: /etc/php8/php.ini
      - source: adminer_config
        target: /etc/php8/php-fpm.d/www.conf
    depends_on:
      mariadb:
        condition: service_healthy
    expose:
      - "9000"
    hostname: inception_adminer
    networks:
      backend:
        ipv4_address: 172.18.0.5
    volumes:
      - adminer_resources:/var/www/adminer
    restart: on-failure

  # REDIS
  redis:
    build:
      context: ./services/redis
    image: redis
    container_name: redis
    configs:
      - source: redis_config
        target: /etc/redis.conf
    env_file: ./.env
    expose:
      - "6379"
    hostname: inception_redis
    networks:
      backend:
        ipv4_address: 172.18.0.6
    restart: on-failure

  # STATIC
  static_www:
    build:
      context: ./services/static_www
    image: static_www
    container_name: static_www
    networks:
      backend:
        ipv4_address: 172.18.0.9
    volumes:
      - static_resources:/var/www/static
    restart: on-failure

  # CADVISOR
  cadvisor:
    privileged: true
    build:
      context: ./services/cadvisor
    image: cadvisor
    container_name: cadvisor
    expose:
      - "8080"
    hostname: inception_cadvisor
    networks:
      backend:
        ipv4_address: 172.18.0.7
    volumes:
      - /:/rootfs:ro \
      - /var/run:/var/run:ro \
      - /sys:/sys:ro \
      - /var/lib/docker/:/var/lib/docker:ro \
      - /dev/disk/:/dev/disk:ro \
    devices:
      - "/dev/kmsg:/dev/kmsg"
    restart: on-failure

  # FTP
  ftp:
    build:
      context: ./services/ftp
    image: ftp
    container_name: ftp
    configs:
      - source: ftp_config
        target: /etc/vsftpd/vsftpd.conf
    env_file: ./.env
    networks:
      backend:
        ipv4_address: 172.18.0.8
    volumes:
      - wp_resources:/home/ghan/
    restart: on-failure

# CONFIGS
configs:
  db_config:
    file: ./services/mariadb/configs/my.cnf
  nginx_global_config:
    file: ./services/nginx/configs/nginx.conf
  nginx_server_config:
    file: ./services/nginx/configs/servers/
  wp_fpm_config:
    file: ./services/wordpress/configs/php.ini
  wp_config:
    file: ./services/wordpress/configs/www.conf
  adminer_fpm_config:
    file: ./services/adminer/configs/php.ini
  adminer_config:
    file: ./services/adminer/configs/www.conf
  redis_config:
    file: ./services/redis/configs/redis.conf
  ftp_config:
    file: ./services/ftp/configs/vsftpd.conf

# NETWORKS
networks:
  backend:
    ipam:
      config:
        - subnet: 172.18.0.0/24
          ip_range: 172.18.0.0/24
          gateway: 172.18.0.1

# VOLUMES
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ghan/data/db
  wp_resources:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ghan/data/wp
  adminer_resources:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ghan/data/am
  static_resources:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ghan/data/st
