version: "3.8"

# PROJECT NAME
name: "inception"

# SERVICES
services:
  mariadb:
    build:
      context: ./services/mariadb
    container_name: maraidb
    configs:
      - source: db_config
        target: /etc/my.cnf
    expose:
      - "3306"
    networks:
      backend:
        ipv4_address: 172.18.0.2
    # profiles:
    #   - back
    volumes:
      - db_data:/var/lib/mysql
    restart: on-failure
    # tty: true
    # wordpress:
    #   build:
    #     context: ./wordpress
    #     container_name: wordpress
    #   depends_on:
    #     mariadb: service_healthy
    #   networks:
    #     backend:
    #       ipv4_address: 172.18.0.3
    #   profiles:
    #     - back
    #     - front
    #   restart: on-failure

    # nginx:
    #   build:
    #     context: ./nginx
    #     container_name: nginx
    #   depends_on:
    #     wordpress: service_healthy
    #   domainname: ghan.42.fr
    #   profiles:
    #     - back
    #     - front
    #   restart: on-failure

    # CONFIGS
configs:
  db_config:
    file: ./services/mariadb/config/my.cnf

# NETWORKS
networks:
  backend:
    ipam:
      config:
        - subnet: 172.18.0.0/24
          ip_range: 172.28.0.0/24
          gateway: 172.18.0.1
    internal: true

# VOLUMES
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ghan/data
  wp_resources:
