version: "3.8"

# PROJECT NAME
name: "inception"

# SERVICES
services:
  mariadb:
    build:
      context: ./services/mariadb
    container_name: maraidb
    configs:
      - source: db_config
        target: /etc/my.cnf
    expose:
      - "3306"
    networks:
      backend:
        ipv4_address: 172.18.0.2
    volumes:
      - db_data:/var/lib/mysql
    restart: on-failure

  wordpress:
    build:
      context: ./services/wordpress
    container_name: wordpress # depends_on:
    expose:
      - "9000"
    #   mariadb: service_healthy
    networks:
      backend:
        ipv4_address: 172.18.0.3
    volumes:
      - wp_resources:/var/www/wordpress
    tty: on
    restart: on-failure

  nginx:
    build:
      context: ./services/nginx
    container_name: nginx
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/inception.conf
    expose:
      - "4242"
    # depends_on:
    #   wordpress: service_healthy
    hostname: ghan.42.fr
    networks:
      backend:
        ipv4_address: 172.18.0.4
    volumes:
      - wp_resources:/var/www/wordpress
    restart: on-failure

# CONFIGS
configs:
  db_config:
    file: ./services/mariadb/configs/my.cnf
  nginx_config:
    file: ./services/nginx/configs/inception.conf

# NETWORKS
networks:
  backend:
    ipam:
      config:
        - subnet: 172.18.0.0/24
          ip_range: 172.28.0.0/24
          gateway: 172.18.0.1

# VOLUMES
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ghan/data/db
  wp_resources:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ghan/data/wp
